version: "3"
services:
  slaves:
    build: ./modbus_simulator
  master:
    build: ./modbus_controller
    depends_on: 
      - slaves
    command:
      - "--hostname"
      - "slaves"
      - "--port"
      - "502"
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "service:slaves"
    capabilities:
      add: ["NET_ADMIN","NET_RAW", "NET_BIND_SERVICE"]
    volumes:
      - ./tcpdump:/tcpdump
    

