version: "3"
services:
  slaves:
    build: ./modbus_simulator
  master:
    build: ./modbus_controller
    depends_on: 
      - slaves
    command:
      - "--hostname"
      - "slaves"
      - "--port"
      - "502"
  tcpdump:
    image: nicolaka/netshoot
    network_mode: "service:slaves"
    depends_on: 
      - slaves
    command: tcpdump -i eth0 -w /tcpdump/modbus.pcap
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    volumes:
      - ./tcpdump:/tcpdump
    

