services:
  slaves:
    build: ./modbus_simulator
  controller:
    build: ./modbus_controller
    depends_on: slaves
    command:
      - "--hostname"
      - "slaves"
      - "--port"
      - "502"
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "service:slaves"
    volumes:
      - ./tcpdump:/tcpdump
